INSERT INTO `mooda`.`products` (`name`, `img`, `description`, `price`, `category`, `quantity`, `intQty`, `collection`, `status`) VALUES ('Robe Red', './src/public/collection2.png', 'robe for summer', '22', 'Women', '4', '4', 'Summer', '0');
INSERT INTO `mooda`.`products` (`name`, `img`, `description`, `price`, `category`, `quantity`, `intQty`, `collection`, `status`) VALUES ('Robe Green', './src/public/collection3.png', 'robe for summer', '22', 'Women', '4', '4', 'Summer', '0');
INSERT INTO `mooda`.`products` (`name`, `img`, `description`, `price`, `category`, `quantity`, `intQty`, `collection`, `status`) VALUES ('Robe Blue', './src/public/rectangle-23@2x.png', 'robe for summer', '22', 'Women', '4', '4', 'Spring', '1');
INSERT INTO `mooda`.`products` (`name`, `img`, `description`, `price`, `category`, `quantity`, `intQty`, `collection`, `status`) VALUES ('Shoes Red', './src/public/collection7.png', 'Shose for Autumn', '22', 'Men', '4', '4', 'Autumn', '0');
INSERT INTO `mooda`.`products` (`name`, `img`, `description`, `price`, `category`, `quantity`, `intQty`, `collection`, `status`) VALUES ('Shoes Blue', './src/public/collection8.png', 'Shose for Autumn', '22', 'Men', '4', '4', 'Spring', '1');
INSERT INTO `mooda`.`products` (`name`, `img`, `description`, `price`, `category`, `quantity`, `intQty`, `collection`, `status`) VALUES ('Shoes Yellow', './src/public/collection9.png', 'Shose for Autumn', '22', 'Men', '4', '4', 'Autumn', '0');
INSERT INTO `mooda`.`products` (`name`, `img`, `description`, `price`, `category`, `quantity`, `intQty`, `collection`, `status`) VALUES ('METAJACKET OG ', './src/public/collection4.png', 'METAJACKET  for Winter', '22', 'Kids', '4', '4', 'Winter', '0');
INSERT INTO `mooda`.`products` (`name`, `img`, `description`, `price`, `category`, `quantity`, `intQty`, `collection`, `status`) VALUES ('MJ Faze Banks', './src/public/collection5.png', ' METAJACKET: Faze Banks for Winter', '22', 'Kids', '4', '4', 'Winter', '0');
INSERT INTO `mooda`.`products` (`name`, `img`, `description`, `price`, `category`, `quantity`, `intQty`, `collection`, `status`) VALUES ('RTFKT X Retrocoin', './src/public/collection6.png', ' The METAJACKET: RTFKT X Retrocoin for Kids', '22', 'Winter', '4', '4', 'Winter', '0');
